---
title: "Take-home Exercise 1"
author: "Wang Shengming"
---

# 1. Setting the Scene

#### City of Engagement, with a total population of 50,000, is a small city located at Country of Nowhere. The city serves as a service centre of an agriculture region surrounding the city. The main agriculture of the region is fruit farms and vineyards. The local council of the city is in the process of preparing the Local Plan 2023. A sample survey of 1000 representative residents had been conducted to collect data related to their household demographic and spending patterns, among other things. The city aims to use the data to assist with their major community revitalization efforts, including how to allocate a very large city renewal grant they have recently received.

# 2. The Task

#### In this take-home exercise, you are required to apply the concepts and methods you had learned in Lesson 1-4 to reveal the demographic and financial characteristics of the city of Engagement, using appropriate static and interactive statistical graphics methods. This exercise requires a user-friendly and interactive solution that helps city managers and planners to explore the complex data in an engaging way and reveal hidden patterns. The data should be processed by using appropriate tidyverse family of packages and the statistical graphics must be prepared using ggplot2 and its extensions.

# 3. Data Description

#### For the purpose of this study, two data sets are provided. They are:

#### Participants.csv

#### Contains information about the residents of City of Engagement that have agreed to participate in this study.

#####   participantId (integer): unique ID assigned to each participant.

#####   householdSize (integer): the number of people in the participant's household

#####   haveKids (boolean): whether there are children living in the participant's household.

#####   age (integer): participant's age in years at the start of the study.

#####   educationLevel (string factor): the participant's education level, one of: {"Low", "HighSchoolOrCollege", "Bachelors", "Graduate"}

#####   interestGroup (char): a char representing the participant's stated primary interest group, one of {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J"}. Note: specific topics of interest have been redacted to avoid bias.

#####   joviality (float): a value ranging from \[0,1\] indicating the participant's overall happiness level at the start of the study.

#### FinancialJournal.csv

#### Contains information about financial transactions.

#####   participantId (integer): unique ID corresponding to the participant affected



#####   timestamp (datetime): the time when the check-in was logged

#####   category (string factor): a string describing the expense category, one of {"Education", "Food", "Recreation", "RentAdjustment", "Shelter", "Wage"}

#####   amount (double): the amount of the transaction
